dir.create("raw_data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results or Tasks")
dir.create("plots")
patient_info<-read.csv(file.choose())
str(patient_info)
patient_info$gender<-as.factor(patient_info$gender)
patient_info$gender_num<-ifelse(patient_info$gender=="Female",1,0)
patient_info$gender_num<-as.factor(patient_info$gender_num)
patient_info$diagnosis<-as.factor(patient_info$diagnosis)
patient_info$diagnosis_num<-factor(patient_info$diagnosis, levels = c("Normal","Cancer"), labels = c("0","1"))
patient_info$diagnosis_num<-as.factor(patient_info$diagnosis_num)
patient_info$smoker<-as.factor(patient_info$smoker)
patient_info$smoker_num<-ifelse(patient_info$smoker=="Yes",1,0)
patient_info$smoker_num<-as.factor(patient_info$smoker_num)
str(patient_info)
write.csv(patient_info,file="C:\\Users\\megha\\Documents\\AI_Omics_Internship_2025\\Module_I\\clean_data\\patient_info_clean.csv")
save.image(file="Meghana_R_Nair_Class_Ib_Assignment.RData")

